Description: AWS DMS Replication Instance
Parameters:
  ProjectName:
    Description: Name of the Service
    Type: String
  Environment:
    Description: Environment launched into
    Type: String
    Default: unspecified
  MultiAzEnabled:
    Type: String
    Description: Multi AZ Enabled
    Default: 'true'
  InstanceClass:
    Type: String
    Description: The cpu and memory capacity of the replication instance
  AllocatedStorage:
    Type: String
    Description: Gigabytes storage for the replication instance
  InstanceIdentifier:
    Type: String
    Description: A name for the replication instance
  EngineVersion:
    Type: String
    Description: Multi AZ Enabled
    Default: '3.1.4'
  CertificatePem:
    Type: String
    Description: Certificate content (rds ca cert / pem file)
    NoEcho: true
  CertificateName:
    Type: String
    Description: Certificate identifier (rds ca cert / pem file name)
  ReplicationSubnetGroup:
    Type: String
    Description: Replication instance subnet group
  VpcId:
    Type: String
    Description: VPC id
  PrivateSubnet:
    Type: String
    Description: Private subnet id
  SecurityGroupId:
    Type: String
    Description: Security group id

Resources:
  ReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupDescription: Replication instance vpc subnet group
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup
      Vpc: !Ref VpcId
      SubnetIds:
        - !Ref PrivateSubnet

  ReplicationInstanceKmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    Properties:
      Description: Key for encrypting DMS replication instance
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':root' ] ]
            Action: 'kms:*'
            Resource: '*'

  BasicCertificate:
    Type: AWS::DMS::Certificate
    Properties:
      CertificateIdentifier: !Ref CertificateName
      CertificatePem: !Ref CertificatePem

  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      PubliclyAccessible: false
      KmsKeyId: !Ref ReplicationInstanceKmsKey
      AllocatedStorage: !Ref AllocatedStorage
      ReplicationInstanceClass: !Ref InstanceClass
      ReplicationInstanceIdentifier: !Ref InstanceIdentifier
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup
      EngineVersion: !Ref EngineVersion
      MultiAZ: !Ref MultiAzEnabled
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId

Outputs:
  InstanceIdentifier:
    Description: Replication instance identifier
    Value: !Ref InstanceIdentifier
    Export:
      Name: !Sub '${ProjectName}:InstanceIdentifier'
  ReplicationInstance:
    Description: replication instance arn
    Value: !Ref ReplicationInstance
    Export:
      Name: !Sub '${ProjectName}:ReplicationInstance'
  CertificateArn:
    Description: SSL cert arn
    Value: !Ref BasicCertificate
    Export:
      Name: !Sub '${ProjectName}:RDSSslCert'
  KmsKeyId:
    Description: KMS id for dms encryption
    Value: !Ref ReplicationInstanceKmsKey
    Export:
      Name: !Sub '${ProjectName}:DMSKmsId'
  Environment:
    Description: Environment launched into
    Value: !Ref Environment
  ProjectName:
    Description: Project name
    Value: !Ref ProjectName
AWSTemplateFormatVersion: 2010-09-09
