Description: AWS DMS endpoints stack
Parameters:
  ProjectName:
    Description: Name of the Service
    Type: String
  Environment:
    Description: Environment launched into
    Type: String
    Default: unspecified
  Name:
    Description: endpoint name
    Type: String
  Type:
    Description: endpoint type (source/target)
    Type: String
  Host:
    Description: database host
    Type: String
  Port:
    Description: database port
    Type: String
    Default: '5432'
  Username:
    Description: database username
    Type: String
  Password:
    Description: database password
    Type: String
  DbName:
    Description: database name
    Type: String
    Default: postgres
  Engine:
    Description: database engine (postgres/mysql/oracle/sqlserver)
    Type: String
    Default: postgres
  SslMode:
    Type: String
    Description: RDS ssl mode none | require | verify-ca | verify-full

Resources:
  Endpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Join [ '-', [ !Ref Name, !Ref Environment,!Ref Type ] ]
      CertificateArn: { 'Fn::ImportValue': !Sub '${ProjectName}:RDSSslCert' }
      ServerName: !Ref Host
      Port: !Ref Port
      Username: !Ref Username
      Password: !Ref Password
      DatabaseName: !Ref DbName
      EndpointType: !Ref Type
      EngineName: !Ref Engine
      KmsKeyId: { 'Fn::ImportValue': !Sub '${ProjectName}:DMSKmsId' }
      SslMode: verify-full
      Tags: 
        - Key: Name
          Value: !Ref Name

Outputs:
  Endpoint:
    Description: DMS Endpoint
    Value: !Ref Endpoint
    Export:
      Name: !Sub '${ProjectName}:${Name}:Endpoint:${Type}:${Environment}'
  Environment:
    Description: Environment launched into
    Value: !Ref Environment
  ProjectName:
    Description: Project name
    Value: !Ref ProjectName
AWSTemplateFormatVersion: 2010-09-09
