Description: DMS tasks stack
Parameters:
  ProjectName:
    Description: Name of the Service
    Type: String
  Environment:
    Description: Environment launched into
    Type: String
    Default: unspecified
  TaskIdentifier:
    Description: An identifier for the replication task
    Type: String
  MigrationType:
    Description: The migration type. Valid values; full-load | cdc | full-load-and-cdc
    Type: String
    Default: full-load
  SourceEndpointArn:
    Type: String
    Description: An Amazon Resource Name (ARN) that uniquely identifies the source endpoint
  TargetEndpointArn:
    Type: String
    Description: An Amazon Resource Name (ARN) that uniquely identifies the target endpoint
  TaskSettings:
    Description: Overall settings for the task, in JSON format
    Type: String
  TableMappings:
    Type: String
    Description: The table mappings for the task, in JSON format

Resources:
  Endpoint:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: !Ref TaskIdentifier
      ReplicationInstanceArn: { 'Fn::ImportValue': !Sub '${ProjectName}:ReplicationInstance' }
      MigrationType: !Ref MigrationType
      ReplicationTaskSettings: !Ref TaskSettings
      TableMappings: !Ref TableMappings
      SourceEndpointArn: !Ref SourceEndpointArn
      TargetEndpointArn: !Ref TargetEndpointArn
      Tags: 
        - Key: Name
          Value: !Ref TaskIdentifier

Outputs:
  Task:
    Description: DMS Task
    Value: !Ref Endpoint
    Export:
      Name: !Sub '${ProjectName}:dms:task:${TaskIdentifier}'
  Environment:
    Description: Environment launched into
    Value: !Ref Environment
  ProjectName:
    Description: Project name
    Value: !Ref ProjectName
AWSTemplateFormatVersion: 2010-09-09
